### ISSUE TITLE
disable autoreloader in production

### ISSUE THREAD

**Issue by binary1230** [magfest/production-config#116]
Just had an error where 'git' was pulling down the files while the server was still running (which.... shouldn't be happening but just did, seperate thing), and the autoreloader tried reloading the half-loaded files, which caused a transient error that was solved with a real restart.

We should disable the autoreloader on production boxes because there's no reason we would need that code to restart itself while it's either in the middle of being edited, or in the middle of being updated.

**Comment by RobRuana** [comment]
This was fixed by:
* https://github.com/magfest/ubersystem-deploy/pull/87
* https://github.com/magfest/production-config/pull/332
* https://github.com/magfest/ubersystem-puppet/pull/183

However, we still need to stop puppet from telling supervisord to restart uber_daemon during a deploy (see https://github.com/magfest/ubersystem-puppet/issues/184).
