### ISSUE TITLE
Changing uber::plugin_magstock::noise_levels

### ISSUE THREAD

**Issue by Hachi05** [magfest/production-config#217]
I want to rename the, what do you call the choices on the left, artifacts? Do we need to do a DB update? Do it on all instances back to Stock 4?

**Comment by kitsuta** [comment]
When you say 'choices on the left' do you mean the variable names, like `quiet`, `conversational`, etc? Doing this will break _everything_ unless we build a DB migration for the instance. What was the idea behind doing so?

If you just mean the text, that's easy, but since you did it with the camping_types I imagine you already know that. :)

**Comment by RobRuana** [comment]
Closing this, as I don't think it's relevant anymore.
